source "https://rubygems.org"

gem 'sinatra', git: 'git@github.com:sinatra/sinatra.git'
gem "shotgun"
gem "haml"
gem "redcarpet"
gem "httparty"
gem "sass"

group :test do
  gem "minitest", require: false
  gem "rack-test"
  gem "pry"
  gem "capybara"
  gem "capybara_minitest_spec"
end